// AUTO-GENERATED by frontend/scripts/gen-api-types.mjs from data_api's OpenAPI schema.
// Do not hand-edit -- regenerate via `npm run codegen` (see that script's own docs).

export interface CandleItem {
  t: number;
  o?: number | null;
  h?: number | null;
  l?: number | null;
  c?: number | null;
  v?: number | null;
}

export interface CandlesResponse {
  items: CandleItem[];
  has_more: boolean;
  venue: string;
}

export interface HealthResponse {
  status: string;
}

export interface IndicatorCatalogEntry {
  params: Record<string, unknown>;
  panel: string;
  category: string;
}

export interface IndicatorConfigEntry {
  name: string;
  params?: Record<string, unknown>;
  category: string;
}

export interface IndicatorSeriesPoint {
  t: number;
  ofi?: number | null;
  obi?: number | null;
  microprice?: number | null;
  spread?: number | null;
}

export interface IndicatorSeriesResponse {
  items: IndicatorSeriesPoint[];
  has_more: boolean;
  venue: string;
}

export interface IndicatorValuesItem {
  t: number;
  values?: Record<string, number | null>;
}

export interface IndicatorValuesResponse {
  items: IndicatorValuesItem[];
  has_more: boolean;
  venue: string;
}

export interface MetricHistoryItem {
  ts: number;
  price?: number | null;
  pct_1h?: number | null;
  pct_24h?: number | null;
  pct_1w?: number | null;
  pct_1m?: number | null;
  volatility?: number | null;
  ofi?: number | null;
  microprice?: number | null;
  spread?: number | null;
  rank?: number | null;
  volume24h?: number | null;
}

export interface MetricsHistoryResponse {
  items: MetricHistoryItem[];
}

export interface RankingsResponse {
  items: Record<string, unknown>[];
  updated_at: number;
  mode: string;
  stale_instrument_ids: string[];
}

export interface SnapshotSeriesPoint {
  t: number;
  bid?: number | null;
  ask?: number | null;
  mid?: number | null;
  micro?: number | null;
  price?: number | null;
}

export interface SnapshotSeriesResponse {
  items: SnapshotSeriesPoint[];
  has_more: boolean;
  venue: string;
}

export interface TechnicalsColumn {
  name: string;
  params?: Record<string, unknown>;
  category: string;
}

export interface TechnicalsValuesResponse {
  values: Record<string, Record<string, number | null>>;
}
