// AUTO-GENERATED by frontend/scripts/gen-api-types.mjs from data_api's OpenAPI schema.
// Do not hand-edit -- regenerate via `npm run codegen` (see that script's own docs).

export interface HealthResponse {
  status: string;
}
