// AUTO-GENERATED by frontend/scripts/gen-api-types.mjs from data_api's OpenAPI schema.
// Do not hand-edit -- regenerate via `npm run codegen` (see that script's own docs).

export interface AlertCreate {
  instrument_id: string;
  level?: number | null;
  frequency: string;
  bar_seconds: number;
  expires_at_ns?: number | null;
  template: string;
  webhook_url: string;
  condition?: unknown | null;
}

export interface AlertResponse {
  instrument_id: string;
  level?: number | null;
  frequency: string;
  bar_seconds: number;
  expires_at_ns?: number | null;
  template: string;
  webhook_url: string;
  id: string;
  status: string;
  created_ns: number;
  last_fired_ns?: number | null;
  condition: unknown;
  condition_text: string;
  invalid_reason?: string | null;
}

export interface AlertUpdate {
  condition: unknown;
  frequency: string;
  expires_at_ns?: number | null;
  template: string;
  webhook_url: string;
  rearm?: boolean;
}

export interface ArchiveRun {
  run_id: string;
  kind: string;
  day: string | null;
  days?: string[] | null;
  started: string;
  finished?: string | null;
  steps: ArchiveStep[];
}

export interface ArchiveRunRequest {
  day?: string | null;
}

export interface ArchiveRunResponse {
  day: string | null;
}

export interface ArchiveStatusResponse {
  next_run: string;
  next_intraday?: string | null;
  running?: ArchiveRun | null;
  last_run: ArchiveRun | null;
  last_intraday?: ArchiveRun | null;
  backup?: string | null;
}

export interface ArchiveStep {
  venue: string | null;
  name: string;
  exit: number;
  duration_s: number;
}

export interface CandleItem {
  t: number;
  o?: number | null;
  h?: number | null;
  l?: number | null;
  c?: number | null;
  v?: number | null;
  partial?: boolean | null;
  buy_v?: number | null;
  sell_v?: number | null;
  buy_n?: number | null;
  sell_n?: number | null;
  pv?: number | null;
  liq_long_v?: number | null;
  liq_short_v?: number | null;
  liq_n?: number | null;
  price_precision?: number | null;
  size_precision?: number | null;
}

export interface CandlesResponse {
  items: CandleItem[];
  has_more: boolean;
  venue: string;
  market: string;
  price_precision: number;
  size_precision: number;
}

export interface ChannelExitCondition {
  kind: string;
  upper: number;
  lower: number;
}

export interface DrawingsResponse {
  items: Record<string, unknown>[];
}

export interface ErrorsResponse {
  counts: Record<string, number>;
  last: Record<string, string>;
  services: Record<string, ServiceErrorSummary>;
}

export interface FilterPresetConditionItem {
  field: string;
  op: string;
  value: number | string;
}

export interface FilterPresetItem {
  name: string;
  conditions: FilterPresetConditionItem[];
}

export interface FilterPresetsResponse {
  presets: FilterPresetItem[];
}

export interface FootprintItem {
  t: number;
  row_ticks: number | null;
  rows: FootprintRow[];
  delta: number | null;
  total: number | null;
  poc_row: number | null;
  no_trades: boolean;
}

export interface FootprintResponse {
  items: FootprintItem[];
  has_more: boolean;
  price_precision: number;
  size_precision: number;
}

export interface FootprintRow {
  p: number;
  b: number;
  s: number;
}

export interface ForcedShareCondition {
  kind: string;
  share: number;
  window_s: number;
}

export interface FundingCondition {
  kind: string;
  rate: number;
}

export interface FundingItem {
  t: number;
  rate: string;
  interval: number | null;
  next_funding_ns: number | null;
  annualised: number | null;
}

export interface FundingResponse {
  has_more: boolean;
  venue: string;
  market: string;
  items: FundingItem[];
}

export interface HealthResponse {
  status: string;
}

export interface IndicatorCatalogEntry {
  params: Record<string, unknown>;
  panel: string;
  category: string;
  choices?: Record<string, string[]>;
  source_selectable?: boolean;
  units?: Record<string, string>;
  outputs: string[];
  plot?: Record<string, string>;
  note?: string | null;
}

export interface IndicatorCondition {
  kind: string;
  name: string;
  params: Record<string, boolean | number | number | string>;
  source?: string;
  output: string;
  op: string;
  value: number;
}

export interface IndicatorConfigEntry {
  name: string;
  params?: Record<string, unknown>;
  category: string;
  source?: string;
  hidden?: boolean;
  style?: Record<string, Record<string, unknown>>;
  instance?: number;
}

export interface IndicatorValuesItem {
  t: number;
  values?: Record<string, number | null>;
}

export interface IndicatorValuesResponse {
  items: IndicatorValuesItem[];
  has_more: boolean;
  errors?: Record<string, string>;
  venue: string;
  market: string;
}

export interface LevelCondition {
  kind: string;
  level: number;
}

export interface LiquidationBarItem {
  t: number;
  long_v?: number | null;
  short_v?: number | null;
  n?: number | null;
  size_precision?: number | null;
  notional_units?: number | null;
  notional_precision?: number | null;
  long_notional_units?: number | null;
  short_notional_units?: number | null;
}

export interface LiquidationBarsResponse {
  has_more: boolean;
  venue: string;
  market: string;
  price_precision: number | null;
  size_precision: number | null;
  items: LiquidationBarItem[];
}

export interface LiquidationItem {
  side: string;
  size_units: number;
  price_units: number;
  price_precision: number;
  size_precision: number;
  venue_event_id: string;
  ts_event: number;
  ts_init: number;
  price_kind: string;
  notional_units: number;
  notional_precision: number;
}

export interface LiquidationNotionalCondition {
  kind: string;
  notional: number;
  window_s: number;
  side?: string | null;
}

export interface LiquidationsResponse {
  has_more: boolean;
  venue: string;
  market: string;
  price_precision: number | null;
  size_precision: number | null;
  items: LiquidationItem[];
}

export interface MarkIndexItem {
  t: number;
  mark?: string | null;
  index?: string | null;
  basis_mi_bps?: number | null;
  basis_ml_bps?: number | null;
}

export interface MarkIndexResponse {
  has_more: boolean;
  venue: string;
  market: string;
  items: MarkIndexItem[];
}

export interface MarketItem {
  instrument_id: string;
  symbol: string;
  venue: string;
  same_asset: boolean;
  market: string;
  volume24h: number | null;
  collected: boolean | null;
}

export interface MarketsResponse {
  items: MarketItem[];
  stale_venues: string[];
}

export interface MetricHistoryItem {
  ts: number;
  price?: number | null;
  pct_1h?: number | null;
  pct_24h?: number | null;
  pct_1w?: number | null;
  pct_1m?: number | null;
  volatility?: number | null;
  ofi?: number | null;
  microprice?: number | null;
  spread?: number | null;
  rank?: number | null;
  volume24h?: number | null;
  funding_rate?: number | null;
  funding_annualised?: number | null;
  open_interest?: number | null;
  oi_change_1h?: number | null;
  oi_change_24h?: number | null;
  basis_mi_bps?: number | null;
  basis_ml_bps?: number | null;
  liq_long_1h?: number | null;
  liq_short_1h?: number | null;
  liq_notional_1h?: number | null;
  liq_ratio_1h?: number | null;
  forced_share_1h?: number | null;
  relative_volume?: number | null;
  high_24h?: number | null;
  low_24h?: number | null;
  range_position_24h?: number | null;
  oi_change_1h_pct?: number | null;
  oi_change_24h_pct?: number | null;
}

export interface MetricsHistoryResponse {
  items: MetricHistoryItem[];
}

export interface OiChangeCondition {
  kind: string;
  pct: number;
  window_s: number;
}

export interface OpenInterestItem {
  t: number;
  oi?: string | null;
  oi_change?: string | null;
}

export interface OpenInterestResponse {
  has_more: boolean;
  venue: string;
  market: string;
  items: OpenInterestItem[];
}

export interface PctMoveCondition {
  kind: string;
  pct: number;
  bars: number;
}

export interface RankingModeRequest {
  mode: string;
}

export interface RankingModeResponse {
  mode: string;
}

export interface RankingsResponse {
  items: Record<string, unknown>[];
  updated_at: number;
  mode: string;
  stale_instrument_ids: string[];
}

export interface ServiceErrorSummary {
  last_start_ns: number | null;
  since_start: Record<string, number>;
  since: Record<string, number> | null;
}

export interface SnapshotSeriesPoint {
  t: number;
  bid_units?: number | null;
  ask_units?: number | null;
  price_precision?: number | null;
  mid?: number | null;
  micro?: number | null;
  price?: number | null;
}

export interface SnapshotSeriesResponse {
  items: SnapshotSeriesPoint[];
  has_more: boolean;
  venue: string;
  market: string;
}

export interface TechnicalsColumn {
  name: string;
  params?: Record<string, unknown>;
  category: string;
  bar_seconds?: number;
}

export interface TechnicalsValuesResponse {
  values: Record<string, Record<string, number | null>>;
  errors?: Record<string, string>;
}

export interface TrendlineCrossCondition {
  kind: string;
  drawing_id: string;
}

export interface WatchlistResponse {
  instruments: string[];
}
