// Ported verbatim (content-wise) from the retired aiohttp dashboard's docs_page.py's KB array,
// as read 2026-09-13 (branch bmad). Story 15.1 Task 4 -- see that story's Completion Notes for the
// section-by-section (docs_page.py KB entry -> this file) checklist.

import type { KbDoc } from "./data";
import { svgArchitecture } from "./diagram";

const architectureHtml = `<figure class="diagram">${svgArchitecture()}<figcaption>The full data path: the three collectors (dYdX, Bybit, Hyperliquid; one <code>capture</code> process per venue) are the only sources of captured market data (the catalog and <code>snapshots:raw</code>; the <code>archive</code> service only consolidates, prunes and rebuilds what they wrote); ranking_engine is the only thing that computes ranking; every UI is a pure reader of Redis. The bots context is the one module sanctioned to run its own TradingNode against a venue directly, with its own data clients (AD-8); inside it only <code>bots/infrastructure/nautilus_host.py</code> imports TradingNode.</figcaption></figure>
<div class="sec"><h2>One paragraph</h2><p>Three per-venue collectors (dYdX, Bybit, Hyperliquid — dYdX opt-in since the venue cutover) pull live market data straight off the Rust adapters and write it to one Nautilus-native Parquet catalog, publishing a live 1-second snapshot feed (<code>snapshots:raw</code>) to Redis as they go. A ranking engine (<code>ranking_engine</code>) reads that feed, scores every coin by volume or volatility, and publishes the result to <code>rankings:live</code>. The web UI, served by <code>data_api</code>, is the only rankings and chart renderer (web-only since Story 25.1a): it reads those two feeds plus the catalog, never recomputing anything itself. <code>bot_tui</code> is the control surface for bots and collectors — it reads <code>bots:status</code>, <code>collector:status</code>, <code>archive:status</code> and <code>markets:live</code>, never market values. Indicators written once in <code>kernel/indicators.py</code> get reused unmodified in Jupyter research, Nautilus backtests, and a live paper-trading bot (the <code>bots</code> context), which publishes its own status to Redis so <code>bot_tui</code> can monitor and start/stop it.</p></div>
<div class="sec"><h2>Module map</h2><table><tr><th>Module</th><th>Role</th><th>Talks to</th></tr>
<tr><td><code>capture/</code></td><td>Captures live dYdX, Bybit and Hyperliquid data → Parquet + <code>snapshots:raw</code>: one <code>CaptureService</code> per venue, wired by <code>capture/venues/&lt;venue&gt;/__main__.py</code> (moved here from the collector packages in Story 26.2)</td><td>dYdX/Bybit/Hyperliquid WS/REST, Redis (publish), catalog (write)</td></tr>
<tr><td><code>research/{domain,application,notebooks,strategies}</code></td><td>Backtest strategies and runners, the watchlist client and the notebooks (Story 24.4) — a pure consumer: reads the catalog through <code>kernel.catalog_files</code> or <code>BacktestDataConfig</code>, rankings over HTTP, and computes no rolling metric of its own. Six executable notebooks (Epic 27) sit on its analysis layer (<code>domain/</code> values, <code>application/</code> ports and services); the notebook index, recipes and local launch are <code>platform/research/README.md</code></td><td>catalog (read), data_api <code>/api/rankings</code> (HTTP)</td></tr>
<tr><td><code>views/</code></td><td>The read models both UIs show (Story 24.2): ranking columns, coin detail, chart series, indicator picker, derivatives and liquidations (Story 33.4), UI preferences — the web UI formats and transports only (rankings and coin detail are web-only since Story 25.1a)</td><td>catalog, candle stores, metrics.db (read-only), Redis (snapshots:raw, rankings:live, liquidations:raw, derivs:raw)</td></tr>
<tr><td><code>ranking/</code></td><td>Sole computer of coin ranking and of the pct-change/volatility math (the <code>RankingBoard</code> aggregate; runs as the <code>ranking_engine</code> service)</td><td>Redis (read snapshots/control/derivs:raw/liquidations:raw, publish rankings:live), metrics.db (write), catalog (read, one-time backfill), venue REST (24h volume)</td></tr>
<tr><td><code>bots/</code></td><td>The actual trading bots — TradingNode + Strategy, paper or gated demo/real-money (its own context since Story 25.3)</td><td>dYdX/Bybit/Hyperliquid WS/HTTP (one data client per venue in use), Redis (bots:status/control)</td></tr>
<tr><td><code>bot_tui/</code></td><td>Keyboard-only terminal UI, interactive/on-demand</td><td>Redis (read bots:status/collector:status/archive:status/markets:live, publish bots:control/collector:control) — no rankings since Story 25.1a and no market values</td></tr>
</table><p>Module boundary rule (AD-4): every module downstream of the collector depends only on shared data types and Redis/HTTP contracts — never another module's internal state. <code>capture</code> never imports from anything downstream of it.</p></div>
<div class="sec"><h2>Redis channel reference</h2><table><tr><th>Channel</th><th>Publisher</th><th>Subscriber</th><th>Payload</th></tr>
<tr><td><code>snapshots:raw</code></td><td>the three collectors (<code>capture</code>)</td><td>ranking_engine, <code>data_api</code> (web UI)</td><td>One DydxSecondSnapshot per instrument per second</td></tr>
<tr><td><code>rankings:live</code></td><td>ranking_engine</td><td><code>data_api</code> (web UI)</td><td>{mode, ranks:[...], stale_instrument_ids} on change + heartbeat</td></tr>
<tr><td><code>ranking:control</code></td><td>data_api (<code>PUT /api/rankings/mode</code>)</td><td>ranking_engine</td><td>Mode-switch request, last-write-wins</td></tr>
<tr><td><code>liquidations:raw</code></td><td>the Bybit collector (<code>capture</code>, Story 33.1)</td><td>ranking_engine, <code>data_api</code> (live candles, then <code>liquidations:{id}</code>)</td><td>One JSON array of <code>Liquidation</code> rows per decoded frame: side, size and bankruptcy price in integer units with their precisions</td></tr>
<tr><td><code>derivs:raw</code></td><td>the three collectors (<code>capture</code>, Story 33.4)</td><td>ranking_engine, <code>data_api</code> (<code>derivs:{id}</code>)</td><td>One JSON array per collector per 1-second sample tick (none when the tick has no rows) of mark, index, funding and open-interest rows, every value exact text; at most once</td></tr>
<tr><td><code>bots:status</code></td><td>bots</td><td>bot_tui</td><td>Per-bot PnL/position/mode/heartbeat, every 5s</td></tr>
<tr><td><code>bots:control</code></td><td>bot_tui</td><td>bots</td><td>{bot_id, action: start|stop} — never a mode field</td></tr>
</table></div>
<div class="sec"><h2>Derivatives and liquidations over HTTP and /ws/live</h2><p>Five read routes (Story 33.4), all on the <code>/api/candles</code> cursor contract (<code>before_ns</code>, <code>limit</code> clamped 1–500, <code>bar_seconds</code> clamped 1–604800), served by <code>views/derivatives.py</code>. A spot id gets an empty page with <code>market: "spot"</code>, never a 404. A missing value is <code>null</code>, never 0.</p><table><tr><th>Route</th><th>Items</th></tr>
<tr><td><code>GET /api/coin/{id}/funding</code></td><td>Each funding update: <code>t</code> (ns), <code>rate</code> (exact text), <code>interval</code> (s), <code>next_funding_ns</code>, <code>annualised</code></td></tr>
<tr><td><code>GET /api/coin/{id}/open-interest</code></td><td>Per bucket: <code>t</code> (ms), the bucket's last <code>oi</code> and <code>oi_change</code> against the previous known bucket, gap rows between</td></tr>
<tr><td><code>GET /api/coin/{id}/mark-index</code></td><td>Per bucket: <code>t</code> (ms), last <code>mark</code> and <code>index</code>, <code>basis_mi_bps</code>, <code>basis_ml_bps</code> (mark against the traded close)</td></tr>
<tr><td><code>GET /api/coin/{id}/liquidations</code></td><td>Each Bybit liquidation: side, integer size and price units, <code>price_kind: "bankruptcy"</code></td></tr>
<tr><td><code>GET /api/coin/{id}/liquidation-bars</code></td><td>Per bucket, untraded buckets included: <code>long_v</code>, <code>short_v</code>, <code>n</code> from the candle store, <code>notional_units</code> summed from the archived raw rows (null unless the archive holds exactly <code>n</code>)</td></tr>
</table><p><code>/ws/live</code> takes <code>{"subscribe": "derivs:{id}"}</code> (each mark, index, funding or OI row of that instrument, as published on <code>derivs:raw</code>) and <code>{"subscribe": "liquidations:{id}"}</code> (each liquidation as <code>{"channel", "liq"}</code>), next to <code>candles:{id}:{bar_seconds}</code>. One socket holds at most 32 subscriptions of all kinds together. A live frame can be lost (pub/sub, a slow socket drops its oldest frame) but never altered; the routes hold the stored history.</p></div>
<div class="sec"><h2>Deployment topology</h2><p>All services bind <code>127.0.0.1</code> only / <code>network_mode: host</code> — nothing is reachable without an SSH tunnel over Tailscale. <code>redis</code>/<code>bybit_collector</code>/<code>hyperliquid_collector</code>/<code>archive</code>/<code>ranking_engine</code>/<code>data_api</code>/<code>dozzle</code> start by default with <code>restart: always</code>. The dYdX <code>collector</code> is explicit opt-in since the venue cutover (<code>profiles: ["dydx"]</code>, <code>make up-dydx</code>; <code>make down-dydx</code> removes it). <code>live-paper</code> is explicit opt-in (<code>profiles: ["live-paper"]</code>, <code>make up-live-paper</code>) with a capped <code>on-failure:5</code> restart policy so a bad config can't crash-loop against a venue's API. <code>bot_tui</code> is a one-shot interactive tool, never a background daemon.</p></div>
<div class="sec"><h2>What's genuinely not finished</h2><ul>
<li><b>DummyStrategy is a wiring proof, not a tuned strategy</b> — by design, but means nothing here is validated to make money.</li>
<li><b>Bot Cache persistence + TUI trades blotter/PnL chart</b> (done, Stories 4.6/4.7) — the Redis-backed Cache, <code>fills.db</code> and <code>bots:history:*</code>.</li>
<li><b>orders_inflight() race guard has no test</b> proving it holds under a real concurrent-fill race.</li>
<li><b>EXTERNAL vs INTERNAL bar aggregation choice</b> picked defensively, never confirmed better against a real dYdX connection.</li>
<li><b>Real-money path (RealMoneyConfig)</b> exists and is gated but has never been exercised even once.</li>
</ul></div>`;

export const KB: KbDoc[] = [
  {
    id: "architecture", group: "start", name: "System Architecture",
    tagline: "What each module owns, and exactly how the pieces talk — Redis channels, SQLite, Parquet, HTTP.",
    html: architectureHtml,
    refs: ["platform/ARCHITECTURE.md"],
  },
  {
    id: "getting-started", group: "ops", name: "Getting Started",
    tagline: "Build the base image, configure instruments, deploy, and reach the web UI remotely over Tailscale.",
    html: `<div class="sec"><h2>First-time setup</h2><p>From <code>platform/</code>:</p><div class="formula">make build-base   # ~15 min, once only — compiles Nautilus from source
make up            # build collector image (seconds) and start collecting
make logs          # tail live collector output
make web           # open Dozzle log viewer (http://localhost:8080)</div></div>
<div class="sec"><h2>Configure instruments</h2><p>Bybit and Hyperliquid read <code>platform/capture/venues/bybit/config.toml</code> / <code>hyperliquid/config.toml</code> (a plain <code>instruments</code> list, e.g. <code>BTCUSDT-LINEAR.BYBIT</code>) at start: edit, then <code>docker compose restart bybit_collector</code>. dYdX runs only after <code>make up-dydx</code> since the venue cutover. Its plan is <code>platform/data/dydx_config.toml</code> (mounted at <code>/app/dydx_collector/config.toml</code>) — hot-reloaded every <code>config_reload_seconds</code> (30s default), no restart needed:</p><div class="formula">[[instruments]]
id = "BTC-USD-PERP.DYDX"</div></div>
<div class="sec"><h2>Open the web UI</h2><p><code>make up</code> starts <code>data_api</code>, which serves this UI at <code>http://localhost:9100</code>. Reads directly from the catalog + Redis, no collector restart needed.</p></div>
<div class="sec"><h2>Remote access via Tailscale + SSH tunnel</h2><p><code>data_api</code> (the web UI), Redis, and Dozzle all bind <code>127.0.0.1</code> only — nothing is reachable from the public internet or even the tailnet directly.</p><div class="formula">ssh -N -L 9100:127.0.0.1:9100 -L 8080:127.0.0.1:8080 you@&lt;vps-tailscale-ip&gt;</div><p>Then open <code>http://localhost:9100</code> (web UI) or <code>:8080</code> (Dozzle) locally. <code>-N</code> holds the tunnel open with no remote shell.</p>
<p><b>Feed-health alerts:</b> set <code>WATCHDOG_NTFY_URL</code> (e.g. an ntfy.sh topic) on each collector service (<code>collector</code>, <code>bybit_collector</code>, <code>hyperliquid_collector</code>) to get a push notification if every subscribed instrument's book goes stale for 30s+ (OBS-01). Without it, the same condition is only logged.</p></div>
<div class="sec"><h2>Inspect the catalog directly</h2><div class="formula">from nautilus_trader.persistence.catalog import ParquetDataCatalog
catalog = ParquetDataCatalog("platform/data/catalog")
catalog.instruments()
catalog.trade_ticks(instrument_ids=["BTCUSDT-LINEAR.BYBIT"])</div></div>`,
    refs: ["platform/README.md"],
  },
  {
    id: "bot-ops", group: "ops", name: "Bot Operations",
    tagline: "Starting/stopping the live paper bot, writing a new strategy, and spotting a stale feed without digging through logs.",
    html: `<div class="sec"><h2>Two separate strategy paths — not interchangeable</h2><table><tr><th></th><th>Backtest / research</th><th>Live paper bot</th></tr>
<tr><td>Where</td><td><code>research/strategies/*_strategy.py</code></td><td><code>bots/strategies/dummy.py</code></td></tr>
<tr><td>Runtime</td><td><code>BacktestNode</code></td><td><code>TradingNode</code> (AD-8 exception)</td></tr>
<tr><td>Wiring</td><td><code>ImportableStrategyConfig</code>, string path</td><td>One strategy hardcoded in <code>node.py</code></td></tr>
<tr><td>Start/stop</td><td>One-shot process call</td><td>Long-running Docker container, Redis pub/sub or bot_tui</td></tr></table></div>
<div class="sec"><h2>Starting/stopping the bots</h2><div class="formula">make up-live-paper   # start (background, live-paper profile)
docker exec dydx-redis redis-cli PUBLISH bots:control '{"bot_id":"bot-01","action":"stop"}'
docker exec dydx-redis redis-cli PUBLISH bots:control '{"bot_id":"bot-01","action":"start"}'</div><p>Stopping does <b>not</b> flatten an open position — no auto-flatten logic exists. A message with the wrong <code>bot_id</code> is silently ignored, so this is safe against a shared Redis instance with multiple bots.</p>
<p>Via <code>bot_tui</code>: <code>make tui</code> → Bots pane (<code>:bots</code>) → highlight → <code>s</code> to start/stop. Stopping a <em>running</em> bot opens a type-to-confirm prompt; starting doesn't. Press <code>v</code> on a bot's detail view to read its strategy source read-only; <code>i</code> to see its incidents log (restarts, feed interruptions), persisted in Redis (<code>bots:incidents:{bot_id}</code>, last 50 kept).</p></div>
<div class="sec"><h2>Writing a new live strategy</h2><ol style="padding-left:20px"><li>New <code>Strategy</code> + <code>StrategyConfig</code> pair in <code>bots/strategies/</code>, following <code>dummy.py</code>'s <code>DummyStrategy</code> as reference.</li><li>Swap the import/instantiation in <code>bots/infrastructure/nautilus_host.py</code>'s <code>build_node()</code>.</li><li>Add new tunables to <code>BotConfig</code>/<code>ExecConfig</code> (<code>bots/domain/config.py</code>), both loaders and <code>config.toml</code>. Never add a <code>mode</code> key — <code>load_paper_config()</code> hard-errors on it by design.</li><li>Rebuild — code is baked into the image, not bind-mounted.</li></ol></div>
<div class="sec"><h2>Spotting downtime without digging through logs</h2><ul><li>A single coin's feed going stale shows as a <code>~ stale feed: SOL-USD-PERP.HYPERLIQUID</code> banner in the web rankings page's status line, from the <code>stale_instrument_ids</code> field (SSOT-04; rankings are web-only since Story 25.1a).</li><li>A bot's own feed going stale, or the process restarting, is in its Incidents log (<code>i</code> key in bot_tui's Bot-detail).</li></ul><p>Neither parses log files — both are computed from data these processes already track.</p></div>`,
    refs: ["platform/docs/BOT_OPERATIONS.md"],
  },
  {
    id: "data-dictionary", group: "data", name: "Data Dictionary",
    tagline: "What the collector actually stores, per raw type — source, cadence, retention, and known dead fields.",
    html: `<div class="sec"><h2>Raw types collected</h2><table><tr><th>Type</th><th>Source</th><th>Cadence</th><th>Downstream use</th></tr>
<tr><td><code>TradeTick</code></td><td>v4_trades WS</td><td>event-driven</td><td class="neg">no longer written</td></tr>
<tr><td><code>OrderBookDeltas</code></td><td>v4_orderbook WS</td><td>event-driven</td><td>applied to in-memory book; stored only if <code>store_order_book_deltas=true</code> (no instrument opts in today)</td></tr>
<tr><td><code>Bar</code></td><td>candles WS</td><td>—</td><td class="neg">never subscribed — dead capability</td></tr>
<tr><td><code>MarkPriceUpdate</code> / <code>IndexPriceUpdate</code></td><td>markets WS</td><td>event-driven</td><td class="neg">stored, no reader found</td></tr>
<tr><td><code>FundingRateUpdate</code></td><td>markets WS</td><td>event-driven</td><td class="neg">stored, no reader found</td></tr>
<tr><td><code>DydxSecondSnapshot</code></td><td>built in-process from book + trades</td><td>every <code>snapshot_interval_seconds</code> (0.5s default)</td><td>the core record — feeds every live indicator on this site</td></tr>
<tr><td><code>OpenInterest</code></td><td>REST poll (stdlib urllib)</td><td>every 300s</td><td class="neg">stored field itself unused; the <em>parallel</em> volume24H liquidity classification from the same poll <b>is</b> used</td></tr>
<tr><td><code>InstrumentStatus</code></td><td>markets WS</td><td>event-driven</td><td class="neg">stored, no reader found</td></tr>
</table><p><code>DydxSecondSnapshot</code> fields: <code>bid_prices/sizes</code>, <code>ask_prices/sizes</code> (top 20 levels), <code>buy_volume/sell_volume</code>, <code>buy_count/sell_count</code>, <code>open/high/low/close_price</code> (this is the collector's only surviving record of traded price now that raw <code>TradeTick</code> is no longer persisted). Every price and size is stored as an exact integer count of <code>10^-price_precision</code> / <code>10^-size_precision</code> (both carried per row; book prices as the best level plus gaps to the level above), never as a float, and becomes a decimal only for a computation or on this page. Every computed indicator on this site's Indicators tab traces back to this one record.</p></div>
<div class="sec"><h2>Guards before a snapshot is ever emitted</h2><p><code>_second_loop</code> skips crossed books (forces a resubscribe after 3s of a persistent cross — see the <a data-nav="kb:pm-crossed-book">crossed-book postmortem</a>) and skips stale books with no deltas for 5s — both DATA-01 “flag the gap, never fabricate” implementations.</p></div>
<div class="sec"><h2>Retention: the honest version</h2><table><tr><th>Type</th><th>Pinned instruments</th><th>Any other dYdX market</th></tr>
<tr><td><code>TradeTick</code></td><td>no longer written</td><td>4h, no longer growing</td></tr>
<tr><td><code>OrderBookDeltas</code></td><td>not stored (nothing opts in)</td><td>not stored</td></tr>
<tr><td>Mark/Index/Funding/Status</td><td class="neg">unlimited</td><td>4h</td></tr>
<tr><td><code>DydxSecondSnapshot</code></td><td class="neg">unlimited</td><td>not collected</td></tr>
<tr><td><code>OpenInterest</code></td><td class="neg">unlimited</td><td>4h</td></tr>
</table><p>Every configured instrument is <code>pinned=true</code>, and pinned instruments are permanently exempt from the prune loop — so mark/index price, funding, open interest, instrument status, and 1s book snapshots for every configured coin accumulate forever with no built-in cap today.</p></div>`,
    refs: ["platform/docs/DATA_DICTIONARY.md"],
  },
  {
    id: "database-setup", group: "data", name: "Database & Persistence",
    tagline: "Four separate storage mechanisms — what each is for, who owns writes, and how to reach it remotely.",
    html: `<div class="sec"><h2>Four mechanisms, no overlap</h2><table><tr><th>Mechanism</th><th>For</th><th>Durable?</th><th>Reachable?</th></tr>
<tr><td>Redis</td><td>Live pub/sub + latest-value cache</td><td>No</td><td>127.0.0.1:6379 only</td></tr>
<tr><td>metrics.db (SQLite)</td><td>31-day rolling per-instrument history</td><td>Yes</td><td>file only</td></tr>
<tr><td>fills.db (SQLite)</td><td>Append-only live-paper fill ledger</td><td>Yes</td><td>file only</td></tr>
<tr><td>Parquet catalog</td><td>Raw market data archive</td><td>Yes</td><td>file only</td></tr>
</table><p>SEC-01 governs every port here: localhost-only, always. Remote access is SSH tunnel only.</p></div>
<div class="sec"><h2>Redis specifics</h2><p><code>redis:8-alpine</code>, container <code>dydx-redis</code>. <b>No persistence, no TTLs, no complex types</b> — if the container restarts, everything is gone and services just republish on their next cycle. Staleness is judged consumer-side (age of the payload's own timestamp), never a Redis expiry. Only plain <code>GET</code>/<code>SET</code>/<code>PUBLISH</code>/<code>SUBSCRIBE</code> — no hashes, sorted sets, streams.</p></div>
<div class="sec"><h2>metrics.db</h2><p>Owned by <code>ranking/infrastructure/metrics_store.py</code>. Table: <code>snapshots(ts, instrument_id, price, pct_1h, pct_24h, pct_1w, pct_1m, volatility, ofi, microprice, spread, rank, volume24h)</code>, upserted every 60s, pruned to 31 days. <b>Writer:</b> ranking_engine exclusively. <b>Reader:</b> data_api only (through <code>views</code> → <code>ranking.application.queries</code>), mounted read-only.</p><p>Note: the <code>ofi</code> column here is the live raw <code>ofi_5</code> (the same tracker the rank entry reads), not the z-scored <code>ofi_10_z</code> the live ranking table leads with.</p></div>
<div class="sec"><h2>fills.db</h2><p>Owned by <code>bots/infrastructure/fills_store.py</code>. Append-only, event-sourced — one row per <code>OrderFilled</code> event. Exists specifically because Nautilus's <code>Cache.positions_closed()</code> silently discards prior closed positions on a NETTING-mode position reopen; <code>fills.db</code> is the durable source of truth trade history is rebuilt from instead.</p></div>
<div class="sec"><h2>config.toml — mutable runtime state, not static config</h2><p>Easy to mistake for a static file, but it's the one file the running system rewrites on its own: every <code>collector:control</code> action (start/unpin/stop/pin_top_liquid) triggers a full rewrite via <code>save_config()</code> — hand-added comments won't survive it. Hot-reloaded every 30s by the collector, so a hand-edit is picked up without a restart.</p></div>
<div class="sec"><h2>Viewing it remotely</h2><table><tr><th>Command</th><th>What it does</th></tr>
<tr><td><code>make remote-db</code></td><td>Tunnels Redis to localhost so a GUI client can connect as if local</td></tr>
<tr><td><code>make remote-web</code></td><td>Tunnels + opens the web UI</td></tr>
<tr><td><code>make remote-tui</code></td><td>SSHes in with a real TTY and runs bot_tui interactively</td></tr>
</table><p>The two SQLite files and the Parquet catalog have no server to tunnel to — <code>rsync</code> a copy down instead.</p></div>`,
    refs: ["platform/docs/DATABASE_SETUP.md"],
  },
  {
    id: "chart-gaps", group: "chart", name: "Gaps: How Missing Data Is Drawn",
    tagline: "A hole in the data takes one chart slot per missing bar, painted in its own colour and labelled with its length — never interpolated.",
    html: `<div class="sec"><h2>What you see</h2><p>When data is missing — a collection outage, a restart, a feed that went quiet — the chart does not close the hole up. Every missing bar keeps its slot on the time axis (every missing <b>second</b> in Lines mode), so a five-minute outage on a 1m chart reads as five missing bars and a six-hour one as six hours. Each slot is drawn as a translucent placeholder bar, one candle wide and the full height of the pane, in the dedicated gap colour (orange, the <code>--chart-gap</code> token; nothing else on the chart uses it). The same slots are painted on the price pane, the volume pane and every indicator pane, aligned slot for slot. The price pane labels each hole at its first slot: <code>no data · 5m</code>, <code>no data · 1m 30s</code>, <code>no data · 3d 4h</code>.</p><p>With the crosshair over a gap slot, the legend shows the same <code>no data · &lt;duration&gt;</code> text in place of the values.</p></div>
<div class="sec"><h2>Never interpolated (AD-F6)</h2><p>A gap slot is empty (native lightweight-charts whitespace): no open/high/low/close, no value, no volume is ever made up for it. Profiles (FRVP/VRVP/SVP), the measurement tool, replay stepping, legend values, the history page and alerts all skip it exactly as before — the orange bar is painted onto the chart canvas (beneath the series, over the grid), never stored in the data. Warm-up whitespace at the start of an indicator (e.g. the first 13 bars of RSI 14) is not a gap and is not painted: gaps are found in the price series only.</p></div>
<div class="sec"><h2>The cap: “(compressed)”</h2><p>One hole takes at most <b>720 slots</b> (<code>MAX_GAP_ROWS_PER_GAP</code>, the same constant in <code>views/chart_series.py</code> and <code>frontend/src/lib/gaps.ts</code>): 12 hours of 1m bars, or 12 minutes of seconds in Lines mode. A longer hole shows its first 720 slots and then the next real bar, and its label says so — <code>no data · 3d 4h (compressed)</code>, with the duration still the hole's real length. Across a compressed hole the time axis is not time-linear; the label is the honest record of how long it was.</p></div>`,
    refs: ["platform/views/chart_series.py", "platform/frontend/src/lib/gaps.ts", "platform/frontend/src/components/chart/primitives/GapPrimitive.ts"],
  },
  {
    id: "chart-legend", group: "chart", name: "Legend Controls: Hide, Settings and Remove",
    tagline: "The legend row is each indicator's control surface: an eye to hide it, a gear for its inputs, price source and line style, and an x to remove it.",
    html: `<div class="sec"><h2>The row</h2><p>Each indicator on the chart has one legend row at the top-left of its pane, in 14px type: the title in the chart's text colour and each output's value in its own line colour. Hover a row or tab to it and three buttons appear: <b>eye</b> (hide / show), <b>gear</b> (settings) and <b>x</b> (remove). Only the row takes pointer events, so a drag or wheel anywhere else on the pane still pans and zooms. The Volume row has the eye and the x only.</p></div>
<div class="sec"><h2>Eye</h2><p>An <b>overlay</b> (a moving average on the price pane) is hidden in place: its lines disappear, the row stays with dimmed values and a crossed eye, and the price pane keeps its size. A <b>pane indicator</b> (RSI, MACD) collapses its whole pane: the page gets shorter by that pane's height, the panes below move up, and its crossed row moves to the price pane's legend. Showing it again re-adds the pane at its old position and height, with no refetch. A hidden row shows its latest value and does not follow the crosshair.</p></div>
<div class="sec"><h2>Gear: the settings modal</h2><p>The modal is titled with the legend title and has three parts. <b>Inputs</b>: every parameter (a dropdown where the catalog lists fixed choices, text validated by type otherwise) plus a <b>Source</b> select (<code>close</code>, <code>open</code>, <code>high</code>, <code>low</code>, <code>hl2</code>, <code>hlc3</code>, <code>ohlc4</code>) for indicators fed the close alone: <code>hl2 = (h+l)/2</code>, <code>hlc3 = (h+l+c)/3</code>, <code>ohlc4 = (o+h+l+c)/4</code>, computed per candle by the backend and never stored. An indicator fed high, low, volume or several fields keeps its fixed input and has no Source. <b>Style</b>: per output a colour (seeded from the pane palette), a width of 1 to 4 px and solid, dashed or dotted; a histogram output has an up and a down colour instead. <b>Footer</b>: Apply, Cancel, Remove. Esc, Cancel or a click on the backdrop closes it with no change.</p><p>A change to the inputs or the source refetches the values; a style-only Apply only restyles the lines already drawn. SMA(20) on <code>close</code> and on <code>hl2</code> are two different instances (the id gets <code>:hl2</code>); the same name, params and source twice is refused.</p></div>
<div class="sec"><h2>Where it is saved</h2><p>In the coin's own <code>chart_indicators.toml</code> entry, next to its params: <code>source</code>, <code>hidden</code> and a <code>style</code> table per output, each written only when not the default, so a file from before loads and saves back unchanged. Adding an indicator is done in the Indicators dialog (there is no list below the chart any more); the Technicals tab on Rankings keeps its own list. The left rail's <b>Cursor</b> button (tooltip "Select / edit drawings (Esc)") is active whenever no drawing tool is armed, including after Esc and after a tool completes. The Volume pane's on/off is not in that file: it is a field of the coin's chart layout (see <a data-nav="kb:chart-layout">Chart Layout</a>), saved on the server, no longer a browser-local setting.</p></div>`,
    refs: ["platform/frontend/src/components/chart/legend.ts", "platform/frontend/src/components/chart/IndicatorSettingsDialog.tsx", "platform/views/indicator_picker.py", "platform/views/preferences.py"],
  },
  {
    id: "chart-layout", group: "chart", name: "Chart Layout: Restored on Return, Default for a New Coin",
    tagline: "A coin's chart comes back exactly as you left it, in any browser, and a coin opened for the first time starts from your default setup.",
    html: `<div class="sec"><h2>What is saved</h2><p>One layout per coin: the <b>timeframe</b>, <b>Candles/Lines</b> mode, the <b>Volume</b> pane on/off, the <b>crosshair</b> toggle, the <b>pane heights</b> you dragged (the height of an indicator you removed is forgotten at your next drag), the <b>zoom</b> (how many bars are on screen) and the <b>volume profile</b> (kind, row count, value-area percent, the session period and HD flag, the fixed range's two anchors, and for the Auto Anchored and TPO profiles the anchor preset, the initial-balance length and the letters switch) and the <b>footprint</b> (on/off, row size, display mode, imbalance ratio, numbers on/off and its two colours when you set them; a layout saved before it loads with the footprint off). Every change is saved on its own, one request per burst of changes; reopening the coin restores all of it before the first candles are requested, so the chart opens on the saved timeframe at the saved zoom with the latest bar at the right edge. Only the zoom is restored, never the scroll position: you always land on live data. Indicators and drawings are not part of the layout; they keep their own files (<code>chart_indicators.toml</code>, <code>chart_drawings.toml</code>).</p></div>
<div class="sec"><h2>Where it is saved</h2><p>One table per instrument id in <code>chart_layouts.toml</code> (<code>v = 1</code>), in the preferences directory (<code>data/preferences/</code>, mounted at <code>/app/preferences/</code>) next to the indicators and drawings files, behind <code>GET</code>/<code>PUT /api/coin/{instrument_id}/layout</code>; the server refuses a layout it cannot store with a 422 naming the key. A browser's old <code>chart-timeframe</code> and <code>chart-volume</code> choices are imported on the coin's first open after Story 32.6 and removed; once the coin has a layout on the server (saved from another browser, say) they are only removed. A saved timeframe or mode this version no longer offers falls back to 1m / Candles with one entry in the error bar, never a blank chart. A failed save shows an alert under the chart and is retried; nothing is saved before the layout has loaded.</p></div>
<div class="sec"><h2>The Layout menu: default for a new coin</h2><p>A coin opened for the first time is seeded from the <code>[default]</code> table of the same file: its layout fields and its indicator list (drawings are never copied); with no default saved it opens as 1m candles with volume on, crosshair on and no indicators. The top toolbar's <b>Layout</b> menu, next to Indicators, has two entries, each behind a confirm. <b>Save as default</b> makes this coin's layout and indicators the default, overwriting the current one. <b>Reset to default</b> replaces this coin's layout and indicators with the default and reloads them; its drawings are kept.</p></div>
<div class="sec"><h2>Known limits</h2><p>Only one volume profile is saved per coin (the highest of session / Auto Anchored / TPO, fixed range, visible range; the profile colours are not saved), and a fixed range outside the loaded bars is restored empty until those bars are loaded. A window resize changes how many bars fit and is saved as a zoom. Two browsers editing one coin overwrite each other (last write wins). The volume row's eye (hide) is not saved.</p></div>`,
    refs: ["platform/frontend/src/hooks/useChartLayout.ts", "platform/frontend/src/lib/chartLayout.ts", "platform/views/preferences.py", "platform/data_api/routes/layout.py"],
  },
  {
    id: "chart-drawings", group: "chart", name: "Drawings: Fibonacci, Long/Short and What Is Saved",
    tagline: "Fibonacci retracement and Long/Short position tools, draggable handles on every drawing, and every drawing kept on the server so it follows you to another browser.",
    html: `<div class="sec"><h2>The tools</h2><p>The left rail's drawing cluster has <b>Trend</b>, <b>HLine</b>, <b>Fib</b>, <b>Long</b>, <b>Short</b>, <b>Measure</b>, <b>FRVP</b>, <b>AVP</b> and <b>AVWAP</b> (the last three are described under Volume Profiles: the Nine Tools). <b>Fib</b> is a drag: press on anchor A, release on anchor B. <b>Long</b> and <b>Short</b> are one click on the entry price. Esc cancels a placement in progress, and Cursor is selected after any placement. Fib, Long and Short stay off until the first candles have arrived, because every price they print is formatted at the instrument's own decimals.</p></div>
<div class="sec"><h2>Fibonacci retracement</h2><p>One line per enabled ratio at <code>B + (A &minus; B) &times; ratio</code>, so 0 sits on B and 1 on A. On by default: 0, 0.236, 0.382, 0.5, 0.618, 0.786, 1; off: 1.272, 1.618, 2.618, 4.236. Each line is labelled "0.618 (price)", a translucent band fills between consecutive levels, the A&ndash;B segment is drawn faintly, and the levels run to the right edge. <b>Settings&hellip;</b> (right-click menu in Cursor mode) turns each ratio on or off and sets its colour, extend-right, the label side and the line width.</p></div>
<div class="sec"><h2>Long and Short</h2><p>The entry is the clicked price. The stop is 1&nbsp;% of the entry away and the target twice that distance the other way (a Long: target above, stop below; a Short: the mirror). The profit zone (entry to target) is green and the loss zone (entry to stop) red, about 20&nbsp;% opaque, from the placed bar to 40 bars later. Labels read "Target: price (+x.xx %)", "Entry: price", "Stop: price (&minus;x.xx %)" and "Risk/Reward: r.rr", recomputed on every drag. <b>Settings&hellip;</b> sets the three prices and the width, and an optional <b>account size</b> and <b>risk %</b> (both or neither) that add "Size: qty" = account &times; risk % &divide; |entry &minus; stop| at the instrument's size precision (rounded down).</p></div>
<div class="sec"><h2>Editing</h2><p>In Cursor mode every drawing has handles, drawn as small squares: a trendline's and a Fibonacci's two anchors; a position's entry (moves the whole box), target, stop and right edge; a horizontal line anywhere along it. A target dragged past the entry, or a stop past it, stops one tick short of the entry. Right-click for colour, delete and Settings&hellip;. A drawing is anchored in time and price, never in pixels, so it stays put when you switch timeframe or between Candles and Lines; a time between two bars is drawn on the earlier bar and the stored anchor is not changed.</p></div>
<div class="sec"><h2>Where it is saved</h2><p>Every drawing &mdash; horizontal lines, trendlines, Fibonacci, positions, Anchored volume profiles and Anchored VWAPs &mdash; is one list per coin in <code>chart_drawings.toml</code> (a table per instrument id with <code>v = 1</code> and a tagged <code>items</code> array), behind <code>GET</code>/<code>PUT /api/coin/{instrument_id}/drawings</code>. The page saves on every change, one request per burst of edits, and restores on load; the server refuses a malformed drawing with a 422 naming the field. The file lives in the one preferences directory (<code>data/preferences/</code>, mounted at <code>/app/preferences/</code>, <code>CHART_PREFERENCES_DIR</code>) next to <code>chart_indicators.toml</code> and <code>screener_columns.toml</code>. The first load after this change imports a browser's old <code>chart-hlines</code> lines once and removes the key.</p></div>`,
    refs: ["platform/frontend/src/lib/drawings.ts", "platform/frontend/src/components/chart/primitives/FibPrimitive.ts", "platform/frontend/src/components/chart/primitives/PositionPrimitive.ts", "platform/views/preferences.py", "platform/data_api/routes/drawings.py"],
  },
  {
    id: "chart-profiles", group: "chart", name: "Volume Profiles: the Nine Tools",
    tagline: "Nine TradingView-style profile tools from the candles on the chart (eight profiles on one engine, plus the Anchored VWAP line): what each anchors to and what it counts.",
    html: `<div class="sec"><h2>One calculation</h2><p>Every tool below is the same calculation, <code>buildVolumeProfile</code> in <code>lib/volumeProfile.ts</code>, drawn by the same <code>VolumeProfilePrimitive</code>; only the window of candles and the trigger differ. The price range of the window is cut into rows; each candle gives its weight to every row its low&ndash;high touches; the row with the most weight is the <b>POC</b> and the <b>value area</b> (70&nbsp;% by default) grows outward from it. Up weight (close &ge; open) and down weight are told apart. Two weights exist: <b>volume</b> (the candle's volume, spread evenly over the rows it touches) and <b>time</b> (the candle counts once in every row it touches, whatever its volume, which is what the TPO needs). All of them read candles, so they draw in Candles mode only.</p></div>
<div class="sec"><h2>The nine tools</h2><table><tr><th>Tool</th><th>Where</th><th>Anchors to</th><th>Counts</th></tr>
<tr><td><b>FRVP</b> Fixed range</td><td>left rail drag</td><td>the two times you drag between (edges are draggable)</td><td>volume, computed once on release</td></tr>
<tr><td><b>VRVP</b> Visible range</td><td>Indicators area</td><td>the bars on screen, from the price axis</td><td>volume, rebuilt on every pan and zoom</td></tr>
<tr><td><b>SVP</b> Session</td><td>Indicators area</td><td>each UTC day, one profile per day (last N)</td><td>volume, from 1-minute bars</td></tr>
<tr><td><b>SVP HD</b></td><td>Indicators area</td><td>as SVP, with more rows that redraw on zoom</td><td>volume</td></tr>
<tr><td><b>PVP</b> Periodic</td><td>Indicators area</td><td>each 4h / daily / weekly / monthly period</td><td>volume</td></tr>
<tr><td><b>Auto Anchored VP</b></td><td>Indicators area</td><td>an anchor, to the latest bar: session, week, month, highest high, lowest low, or auto</td><td>volume</td></tr>
<tr><td><b>Anchored VP</b> (AVP)</td><td>left rail, one click</td><td>the bar you click, to the latest bar</td><td>volume</td></tr>
<tr><td><b>Anchored VWAP</b> (AVWAP)</td><td>left rail, one click</td><td>the bar you click, onward</td><td>a line, not a histogram: volume-weighted average price</td></tr>
<tr><td><b>TPO</b> Time Price Opportunity</td><td>Indicators area</td><td>each UTC day (or another period), like SVP</td><td>time: one count per 30-minute candle per row it touches</td></tr>
</table><p>SVP, SVP HD, PVP, Auto Anchored VP and TPO share one slot: the chart shows at most one of them at a time, and picking another replaces it.</p></div>
<div class="sec"><h2>Auto Anchored VP</h2><p>The profile runs from the anchor to the latest bar and is marked by a dashed vertical line at the anchor. Presets: <b>Session</b> (the start of the current UTC day), <b>Week</b> (Monday 00:00 UTC), <b>Month</b>, <b>Highest high</b> and <b>Lowest low</b> (the bar holding that extreme of the loaded bars) and <b>Auto</b>, which picks by the chart's bar size: a session up to 15-minute bars, a week up to 4-hour bars, a month above. The anchor is re-resolved on every new bar, so a session or week rollover moves it, and again on every timeframe change. The calendar anchors are profiled from their own fetch (the finest bar the period affordably allows), so they do not depend on how far back the chart has loaded; a period the fetch could not fully cover is not drawn rather than drawn truncated. Rows, value area and colours are in the settings panel.</p></div>
<div class="sec"><h2>Anchored VP and Anchored VWAP</h2><p>Arm <b>AVP</b> or <b>AVWAP</b> and click a bar; the tool disarms after the click. In Cursor mode drag the square handle to move the anchor to another bar. <b>Settings&hellip;</b> in the right-click menu opens a modal: for the profile the rows (2 to 500), the value area and the two colours; for the VWAP the <b>source</b> (<code>hlc3</code> by default, <code>close</code> or <code>ohlc4</code>), the <b>bands</b> and the two colours. The VWAP is <code>sum(source &times; volume) / sum(volume)</code> from the anchor bar onward; the bands are &plusmn;1 and &plusmn;2 volume-weighted standard deviations of the source around it (<code>sum(v &times; (s &minus; vwap)^2) / sum(v)</code>, solid for &plusmn;1&sigma;, dashed for &plusmn;2&sigma;). A bar without volume adds no point, so the line starts at the first bar that has volume. The current value is in the legend at the instrument's own decimals. Both are saved with the coin's drawings.</p></div>
<div class="sec"><h2>TPO</h2><p>The TPO counts, for each price row, how many 30-minute candles of the session touched it, and draws each count as blocks side by side (one block per candle-touch; a row touched more than 30 times draws 30 blocks and one longer bar for the rest, so its length stays proportional). The POC row is outlined and the value area shaded as in a volume profile. The <b>initial balance</b> is the high&ndash;low of the bars that open in the session's first minutes (60 by default, 2 &times; 30m; set in minutes, counted in whole 30-minute bars, so 45 takes two) and is outlined as a dashed box across the profile. The <b>Letters</b> option, off by default, draws the touching candle's letter in each block instead of a plain block: A is the session's first 30 minutes, B the next, and so on by time, so a missing bar leaves its letter out.</p></div>
<div class="sec"><h2>Known limits</h2><p>The spread is per candle, not per trade: a candle's volume is smeared evenly over its range. For where inside a bar each trade actually happened, turn on the per-trade footprint (see <a data-nav="kb:chart-footprint">Volume Footprint</a>). An Anchored VP or VWAP whose anchor is older than the bars the chart has loaded is not drawn until you scroll back far enough to load that bar, because a VWAP started mid-history would misstate it. The TPO period is fixed at 30 minutes. Anchored drawings include the forming bar, so their line and profile move with it. The profile colours are not saved with the layout; the settings that are (kind, rows, value area, period, anchor, initial balance, letters) are restored when you return to the coin.</p></div>`,
    refs: ["platform/frontend/src/lib/volumeProfile.ts", "platform/frontend/src/lib/autoAnchor.ts", "platform/frontend/src/lib/anchoredVwap.ts", "platform/frontend/src/lib/tpo.ts", "platform/frontend/src/components/chart/primitives/VolumeProfilePrimitive.ts"],
  },
  {
    id: "chart-footprint", group: "chart", name: "Volume Footprint: Trades per Price inside Each Bar",
    tagline: "Each closed bar split into price rows from the raw trade archive: sell × buy per row, delta, total, POC and diagonal imbalances, never fabricated for the forming bar.",
    html: `<div class="sec"><h2>Turning it on</h2><p>Open <b>Indicators</b> and tick <b>Footprint</b>, pinned next to Volume. It draws in Candles mode only (in Lines mode the dialog says so and nothing is fetched). The price pane's legend gets a <b>Footprint</b> row showing the display mode and the row size, with a gear (settings) and an x (off). On/off and every setting are saved in the coin's layout (see <a data-nav="kb:chart-layout">Chart Layout</a>).</p></div>
<div class="sec"><h2>What a bar shows</h2><p>Every executed trade the archive holds for the bar (price, size, aggressor side, from <code>data/trade_tick/</code>) is put in a price <b>row</b>: <code>row = price // row_ticks × row_ticks</code> in the instrument's own price units. <b>Auto</b> row size (the default) is the smallest number of ticks that gives at most 24 rows over the bar's traded range, chosen per bar, so rows of neighbouring bars can differ in size; a fixed size (1 tick and up) is the same for every bar and its rows line up across bars, except that a bar whose range would need more than 1000 rows is drawn at the smallest multiple of the size that fits. Each row is a cell: the left half is the <b>sell</b> side (seller-initiated trades, plus the rare trade with no aggressor, the candle fold's rule, so the rows add up to the candle's volume), the right half the <b>buy</b> side. Cells are shaded on a heat scale of the bar's fullest row; the row with the most volume, the <b>POC</b>, is outlined. Under the bar's lowest row the footer prints the bar's <b>delta</b> (buy − sell, green when positive, red when negative) and <b>total</b>. The candle is still drawn under the cells, dimmed.</p></div>
<div class="sec"><h2>Display modes</h2><table><tr><th>Mode</th><th>Cell text</th><th>Cell colour</th></tr>
<tr><td><b>Bid × Ask</b> (default)</td><td>sell × buy</td><td>sell half in the sell colour, buy half in the buy colour</td></tr>
<tr><td><b>Delta</b></td><td>buy − sell</td><td>the buy colour when buy ≥ sell, else the sell colour</td></tr>
<tr><td><b>Volume</b></td><td>buy + sell</td><td>neutral grey</td></tr>
</table><p>Every number is printed from exact integer units through <code>lib/units.ts</code> at the instrument's size precision (never through a float). Below a bar spacing of 40 px (zoomed out) the numbers hide and the cells stay as heat; a number wider than its column is not drawn. <b>Numbers</b> off in the settings hides them at every zoom.</p></div>
<div class="sec"><h2>Imbalances</h2><p>Diagonal, as on an order-flow chart: a row's <b>buy</b> is an imbalance when it is at least <i>ratio</i> times the <b>sell</b> one row below (the ask lifted against the bid hit just under it), outlined in green on the buy half; a row's <b>sell</b> is an imbalance when it is at least <i>ratio</i> times the <b>buy</b> one row above, outlined in red on the sell half. The ratio is 3 by default (settable, at least 1). A row next to one that did not trade compares against zero, so any buy at a bar's lowest row and any sell at its highest count; a side that did not trade is never an imbalance.</p></div>
<div class="sec"><h2>Settings</h2><p>The legend gear opens <b>Inputs</b> (row size Auto or fixed ticks, display mode, imbalance ratio) and <b>Style</b> (numbers on/off, buy and sell colours, default colours). Apply refetches only when the row size changed; any other change only redraws.</p></div>
<div class="sec"><h2>Known limits</h2><p><b>Historical only.</b> A bar gets a footprint once it closed and settled: the server serves only bars that ended at least 7 minutes ago (a reconnect's trade backfill can still archive a trade up to 5 minutes late, plus two collector flushes), and the page checks for new bars once a minute (once the next bar can have closed), so the forming bar and the last few minutes never have one. Nothing is ever made up for them from the 1-second snapshots. Upgrade path: fold the live <code>trades</code> stream in the candles context. A bar the archive holds no trade for is painted in the gap colour, never drawn as zeros. The footprint reaches back only as far as the raw trade archive does: a day's trades (<code>data/trade_tick/</code>) are released 7 days after that day reconciled against the venue (<code>--trade-retention-days</code>), so an older bar has no trades and shows the gap colour while its candle stays. Rows add up exactly to the candle's volume on rebuilt days; a live (not yet rebuilt) minute can differ by a late trade the nightly rebuild places. One page is at most 200 bars and 7 days of span.</p></div>`,
    refs: ["platform/views/chart_series.py", "platform/kernel/catalog_files.py", "platform/data_api/routes/footprint.py", "platform/frontend/src/lib/footprint.ts", "platform/frontend/src/hooks/useFootprint.ts", "platform/frontend/src/components/chart/primitives/FootprintPrimitive.ts"],
  },
  {
    id: "backtesting", group: "backtest", name: "Backtesting & Strategies",
    tagline: "Which existing backtest runner to copy, how to build a strategy, and how to wire it in.",
    html: `<div class="sec"><h2>Which existing backtest to copy</h2><table><tr><th>Data granularity</th><th>Feed</th><th>Copy</th></tr>
<tr><td>Bars (aggregated from trades)</td><td><code>TradeTick</code> → internal <code>Bar</code></td><td><code>research/strategies/backtest_dydx.py</code></td></tr>
<tr><td>Raw 1s book snapshots</td><td><code>DydxSecondSnapshot</code></td><td><code>research/strategies/backtest_snapshot.py</code></td></tr>
<tr><td>Raw 1s book snapshots, fills at the snapshot's best bid/ask</td><td><code>DydxSecondSnapshot</code> + <code>QuoteTick</code> from <code>kernel.catalog_files.query_top_of_book</code></td><td><code>research/strategies/backtest_ofi.py</code></td></tr>
</table><p>Strategies are referenced by string path, <code>research.strategies.&lt;module&gt;:&lt;Class&gt;</code>. Don't write a new backtest runner from scratch — copy the closest match and swap the <code>strategy_path</code>/<code>config_path</code>/<code>data=[...]</code> list. <code>backtest_dydx.py</code> defaults to backtesting every coin in the live Watchlist (needs <code>data_api</code> running); pass <code>symbols=[...]</code> to skip that dependency.</p></div>
<div class="sec"><h2>Strategy conventions (every *_strategy.py follows these)</h2><ul>
<li><code>frozen=True</code> on the config class.</li>
<li><code>on_start</code>: look up <code>self.instrument</code> via <code>self.cache.instrument(...)</code>; <code>self.stop()</code> + log an error if missing, never assume it's there.</li>
<li>Subscribe to exactly the feeds needed — <code>subscribe_bars</code>, <code>subscribe_trade_ticks</code>, <code>subscribe_order_book_deltas</code>, or <code>subscribe_data(DataType(DydxSecondSnapshot), ...)</code> for the pre-computed snapshot.</li>
<li>Position checks via <code>self.portfolio.is_flat/is_net_long/is_net_short</code>, never hand-rolled tracking.</li>
<li>Reuse <code>kernel/indicators.py</code> — never reimplement OFI/OBI/microprice/spread inline. Research never imports <code>views/</code>, <code>data_api/</code> or <code>ranking/</code>, and reads market-data rows only through <code>kernel.catalog_files</code> or <code>BacktestDataConfig</code>.</li>
</ul></div>
<div class="sec"><h2>Wiring a strategy into a backtest run</h2><ol style="padding-left:20px"><li>Point <code>strategy_path</code>/<code>config_path</code> at the new files.</li><li>List every <code>BacktestDataConfig</code> the strategy subscribes to — missing one means the subscription silently gets no data, no error.</li><li>Custom types (e.g. <code>DydxSecondSnapshot</code>) need an explicit <code>client_id=str(venue)</code> and usually a parallel <code>TradeTick</code> config purely for instrument auto-registration.</li><li>The catalog holds no <code>Bar</code> (minute bars were retired on 2026-09-20, D-35) — aggregate internally from <code>TradeTick</code> (the Story 22.13 raw trade archive).</li></ol><p>Trust <code>BacktestResult.stats_pnls</code>/<code>stats_returns</code> for whether trades happened — <code>total_orders</code>/<code>total_positions</code> were found unreliable (sometimes 0 despite real fills) in this pinned nautilus_trader version.</p></div>
<div class="sec"><h2>Notebooks</h2><p>Six executable notebooks in <code>research/notebooks/</code> (catalog inspection, microstructure, correlation, backtest evaluation, Monte Carlo, candlestick scanner), each a jupytext pair run against a fixture archive by <code>make test</code>; every number comes from <code>research/domain</code>, <code>research/application</code> or <code>kernel</code>, never a formula in a cell (NB-01). <code>04_backtest_evaluation</code> is the one way to evaluate a strategy interactively. The index, the recipes (a notebook, a metric, a pattern), the local launch and this page's full backtest how-to are <code>platform/research/README.md</code>.</p></div>`,
    refs: ["platform/research/README.md"],
  },
  {
    id: "pm-crossed-book", group: "postmortem", name: "Crossed-Book Root Cause",
    tagline: "72% of crossed-book episodes proven to be our own pipeline's fault, not the venue's — exact locus still open.",
    status: "open",
    html: `<div class="sec"><p><b>Standard applied:</b> DATA-02 — detect-and-recover is not sufficient, the exact mechanism must be known. <b>Status: <span class="neg">still genuinely open</span></b>, not quietly resolved just because the visible symptom is smaller.</p></div>
<div class="sec"><h2>Symptom</h2><p>The collector's <code>_second_loop</code> frequently logs “Crossed book” (bid ≥ ask) for BTC/ETH and other liquid instruments, escalating to a forced resubscribe if it persists.</p></div>
<div class="sec"><h2>Two timing bugs found and fixed along the way</h2><ul>
<li><b><code>_CROSSED_RESYNC_NS</code> 15s → 3s.</b> A real desync never self-heals from more deltas alone; waiting 15s before forcing a resubscribe was pure downside (the module constant became the config field <code>CoreConfig.crossed_resync_seconds</code> in Story 22.2, whose default today is 10s).</li>
<li><b><code>_flush_loop</code>'s periodic Parquet write was blocking the event loop.</b> <code>write_data()</code> ran synchronously on the event-loop thread every <code>flush_interval_seconds</code> (60s), during which crossed-book detection couldn't run at all. <span class="callout">An earlier fix attempt was wrong</span> — assumed the cause was delta-processing bursts and built a decoupled ingest queue; that helped but didn't fix it. The staleness canary's suspiciously exact ~69–71s periodicity (matching the 60s flush interval almost exactly) is what pointed at the real cause. Actual fix: <code>_flush_once</code> now offloads the write via <code>asyncio.to_thread</code>.</li>
</ul></div>
<div class="sec"><h2>Permanent instrumentation kept in production</h2><ul><li>Per-side last-delta timestamps in every crossed-book log line.</li><li><code>_second_loop</code> staleness canary (2s slack) — the thing that caught the wrong first diagnosis above.</li><li><code>nautilus_pyo3.init_logging()</code> now called in <code>main()</code> — this collector never went through TradingNode/Kernel startup, so every Rust-side <code>log::error!</code>/<code>warn!</code> in the whole dYdX adapter was silently dropped, never emitted, before this fix.</li></ul></div>
<div class="sec"><h2>The decisive experiment</h2><p>Built an independent reference WS client — pure Python + aiohttp, zero shared code with nautilus_trader — connecting directly to dYdX's indexer, maintaining its own naive book, and dumping an episode file the instant the real collector logged a crossed book.</p>
<table><tr><th>Result</th><th>Count</th><th>Meaning</th></tr>
<tr><td>Reference client matches collector's (wrong) reading</td><td>16</td><td>genuine venue-side crossing — dYdX's own served book really is crossed (expected under dYdX v4's per-validator, pre-consensus book architecture)</td></tr>
<tr><td class="neg">Reference client diverges (shows correct data collector doesn't)</td><td><b>41 (72%)</b></td><td class="neg">our own pipeline provably lost/failed to apply data the venue actually sent</td></tr>
</table><p>Byte-level proof for one BTC-USD episode: dYdX sent an ask-level removal; the reference client correctly moved its ask; the collector's book never reflected it. Narrowed to exactly two possibilities: a connection-specific transport-level loss unique to our WS connection, or a silent failure inside the Rust WS handler (audited — no silent-drop path found in <code>crates/adapters/dydx/src/websocket/handler.rs</code>).</p></div>
<div class="sec"><h2>Open question</h2><p>Pinning down category 2's exact locus. Three options were laid out: (A) TLS-intercept the collector's own connection — blocked, requires patching <code>crates/</code> which FORK-01/02 forbid without an explicit exception; (B) stop here — explicitly rejected given DATA-02; (C) run 2–3 independent reference clients against <em>each other</em>, not just vs. the collector — no crates/ changes needed, ~1 hour of work, <b>recommended next step, not yet built.</b></p></div>`,
    refs: ["platform/.planning/debug/crossed-book-root-cause.md", "platform/CLAUDE.md DATA-02, DATA-04"],
  },
  {
    id: "pm-nifelheim", group: "postmortem", name: "Nifelheim Resource Exhaustion",
    tagline: "Stale books across nearly every instrument + ranking_engine's silent restart loop, both traced to one root cause: the VPS is oversubscribed.",
    status: "deferred",
    html: `<div class="sec"><p><b>Status:</b> mechanism identified (DATA-02 standard met). <b>No fix applied</b> — infra decision deferred by the user.</p></div>
<div class="sec"><h2>Symptom</h2><p>Widespread “Stale book” warnings across nearly every subscribed instrument (BTC/ETH/SOL included) — 31 <code>_second_loop tick arrived Ns late</code> events (2–21.5s late) over a 95-minute window, each followed by a stale-book burst hitting ~27–28 of ~28 instruments simultaneously.</p></div>
<div class="sec"><h2>Root cause: host CPU + memory oversubscription</h2><p>2 vCPU / 3.7GB, 0 swap. <code>uptime</code> load average 10.85 on a 2-core box (4–5× oversubscribed). <code>dydx-collector</code> alone at 105% CPU continuous; <code>dydx-ranking-engine</code> RestartCount=430, cycling every ~2 minutes — caught live via <code>docker events</code>: <code>container oom → die (exitCode=137) → start</code>. This is the <b>host's global OOM-killer</b>, confirmed not a container memory cap (<code>Memory=0</code>, uncapped) and not a code-level exit path (grepped — no <code>sys.exit</code>/unhandled-exception path exists in <code>engine.py</code>).</p><p><code>free -h</code>: 119Mi free / 1.0Gi available out of 3.7Gi — essentially no slack before <code>ranking_engine</code> even accumulates its rolling-window state.</p></div>
<div class="sec"><h2>Why this wasn't caught earlier</h2><p>A prior instance of the same failure class (2026-09-11, <code>compute_all()</code> defaulting to ~300 instruments × 25h lookback × 32-way concurrency) was already fixed once by scoping to only pinned/live instruments — that reduced per-cycle memory but didn't add headroom, and a later commit that bumped the collector's instrument cap re-triggered the same OOM class under a new guise: a silent restart loop instead of an obvious one-time crash.</p></div>
<div class="sec"><h2>Options discussed, none chosen</h2><ol style="padding-left:20px"><li>Add swap — quick, reversible, doesn't fix CPU oversubscription, trades OOM-kills for thrashing under sustained pressure.</li><li>Resize the VM — addresses the actual root cause, provider-side action.</li><li>Reduce load — fewer instruments, or move dashboard, bot_tui or ranking_engine off this box.</li><li><b>(Chosen for now) Document and defer.</b></li></ol></div>
<div class="sec"><h2>Addendum (Epic 13, Story 13.1)</h2><p><code>_slow_loop_task</code> now passes <code>max_workers=4</code> to <code>compute_all()</code> (was 32) — bounds concurrent Parquet reads on the 60s cycle. An explicit small mitigation, <b>not</b> a resolution of the underlying CPU/RAM oversubscription. Real before/after <code>docker stats</code> evidence was not collected (no SSH access from this dev environment) — whether this measurably reduces the OOM rate in production is still an open, deferred verification. Story 13.2 is the actual fix: removes the recurring Parquet re-scan from the hot path entirely.</p></div>`,
    refs: ["platform/.planning/debug/nifelheim-resource-exhaustion-2026-09-12.md"],
  },
  {
    id: "fix-flatline", group: "fixed", name: "Bid/Ask Flatline on Coin Chart",
    tagline: "A per-coin chart's bid/ask froze during WS reconnect recovery while the homepage kept moving — root-caused and fixed.",
    status: "done",
    html: `<div class="sec"><p><b>Symptom:</b> an individual coin's chart in the dashboard would freeze bid or ask (sometimes both) while other data kept updating and the venue's own price was clearly still moving. Silent failure, no log errors.</p></div>
<div class="sec"><h2>Root cause</h2><p><code>_live_books[iid]</code> is frozen during WebSocket reconnect recovery. When the dYdX WS reconnects, the Rust client re-subscribes instruments at a 2/sec rate limit — the last instrument in the sorted subscription queue waits up to N/2 seconds for its fresh snapshot. During that window, <code>_second_loop</code> had no staleness check and repeatedly emitted the pre-reconnect (stale) book state. Plotly's <code>mode=lines</code> then drew a straight, misleading line across that flat stretch.</p></div>
<div class="sec"><h2>Fix (two parts)</h2><ol style="padding-left:20px"><li><code>collector._second_loop</code> tracks <code>_last_book_update_ns</code> per instrument and skips snapshot emission once a book hasn't received deltas in &gt;5s — stops stale data from ever reaching Redis.</li><li>the retired dashboard's <code>_coin_chart_json</code> detects gaps &gt;2.5s between consecutive snapshot timestamps and inserts a null — Plotly then draws an honest break instead of a flat line.</li></ol><p>Verified across 46/46 tests, including 4 new gap-detection tests exercising the null-insertion path directly.</p></div>
<div class="sec"><h2>Addendum (Story 32.1)</h2><p>The one-null-per-gap break above is superseded: the retired Plotly dashboard's check now lives in <code>views/chart_series.py</code> (same 2.5s threshold), which emits one empty row per missing second, so a Lines-mode hole keeps its real length and is painted in the gap colour — see the Chart entry “Gaps: How Missing Data Is Drawn”.</p></div>`,
    refs: ["platform/.planning/done/bid-ask-flatline-coin-chart.md"],
  },
  {
    id: "fix-unpin-exclude", group: "fixed", name: 'Unpin → config.exclude, with confirm',
    tagline: 'Folded the collector\'s separate "unpinned" list into the existing exclude denylist, and added a type-to-confirm guard before unpinning.',
    status: "done",
    html: `<div class="sec"><h2>What changed</h2><ol style="padding-left:20px"><li><code>"unpin"</code> now writes straight into <code>config.exclude</code> instead of a separate <code>CollectorConfig.unpinned</code> field, which was dropped entirely.</li><li>bot_tui's “unpinned” section now reflects <code>config.exclude</code> as a whole — a coin hand-added to <code>exclude</code> in <code>config.toml</code> shows up there too, no separate “via unpin” distinction any more.</li><li>Pressing <code>p</code> to unpin now opens the same type-to-confirm prompt pattern already used for <code>x</code>/stop, instead of firing immediately.</li></ol></div>
<div class="sec"><h2>Why this is a real behavior change, not just a rename</h2><p><code>classify_liquidity</code> already treats every id in <code>exclude</code> as permanently illiquid regardless of volume — a hand-curated denylist for stablecoins/garbage markets. Folding <code>unpin</code> into it means an unpinned coin is now <em>also</em> permanently labeled “illiquid” in <code>collector:status</code>, not just “not currently collected.” Presumably the intended strength, called out explicitly so it isn't a surprise later.</p></div>
<div class="sec"><h2>Design note taken</h2><p>The confirm-guard implementation was generalized into one shared “pending collector action” state (action-name parameterized) rather than duplicating the stop-confirm's four methods a second time — in line with this repo's deletion-over-addition preference (DESIGN-03) given the two flows would otherwise be near-identical.</p></div>`,
    refs: ["platform/.planning/done/collector-unpin-exclude-confirm.md"],
  },
  {
    id: "fix-ranking-clarity", group: "fixed", name: "Ranking Table: Vol Label + Lean Placement",
    tagline: "Disambiguated the ranking table's bare “Vol” column and moved microprice lean off the cross-instrument table onto the single-coin page.",
    status: "done",
    html: `<div class="sec"><p><b>Date:</b> 2026-09-13. <b>Trigger:</b> both the web ranking table and bot_tui's Coins pane showed a bare <code>“Vol”</code> header sitting on the same row as <code>“Vol Score”</code> and <code>“Vol24h”</code> — three different numbers, one ambiguous name. The same table also showed <code>“u lean”</code> (microprice lean), a single-coin directional signal, mixed in among the cross-coin ranking columns.</p></div>
<div class="sec"><h2>Change</h2><ul>
<li>Relabeled the <code>volatility</code> ranking-table column from <code>“Vol”</code> to <code>“Vol(catalog)”</code> in the ranking-columns module (today <code>views/ranking_columns.py</code>; the single SSOT both the web table and bot_tui's Coins pane render from) and in the web dashboard's client-side ranking-table script — matching the label the coin-detail page already used for the same field, so it now reads identically everywhere it appears. See <a data-nav="i:vol_catalog">Vol(catalog)</a> for the full definition.</li>
<li>Moved <code>microprice_lean</code> out of <code>RANKING_COLS</code> (shared by both ranking tables) into <code>_HISTORY_ONLY_COLS</code> — the same mechanism already used to keep <code>rank</code> off the live table. It's still shown on both single-coin detail views (web + bot_tui) and now also still charts correctly on the 31-day history page. See <a data-nav="i:microprice_lean">Microprice Lean</a>.</li>
</ul></div>
<div class="sec"><h2>Why this approach</h2><p><code>_HISTORY_ONLY_COLS</code> already existed for exactly this purpose (“field charted on the coin's history page, not shown as a ranking-table column”) — reusing it instead of introducing a second parallel list keeps the SSOT intact (platform/CLAUDE.md SSOT-04) and required touching only the column metadata, not either UI's rendering code.</p></div>`,
    refs: ["platform/views/ranking_columns.py"],
  },
  {
    id: "self-hosted-docs", group: "fixed", name: "Signal Atlas moved self-hosted",
    tagline: "This page itself: first served by the retired aiohttp dashboard at /docs, ported to the React UI by Story 15.1.",
    status: "done",
    html: `<div class="sec"><p>Originally built as a standalone Claude Artifact so it could be reviewed before committing to a permanent home. Moved into the aiohttp dashboard's <code>docs_page.py</code> and served at <code>/docs</code> — same content model (client-side hash-routed, data-driven indicator/KB pages), retheme only: the light/adaptive-theme CSS was dropped for one fixed dark palette matching <code>dashboard.py</code>'s own <code>_CSS</code> (<code>#0d1117</code>/<code>#161b22</code>/<code>#21262d</code>/<code>#58a6ff</code>, the same GitHub-dark-style tokens already used throughout the ranking table and charts), and the Google-Fonts IBM Plex pairing was dropped for the app's existing plain <code>monospace</code> stack so this page doesn't make an external request the rest of the app doesn't already make. Story 15.1 (this repo's chart-frontend-rewrite epic) ported this same content again, from the aiohttp dashboard.py into a React page — see that story for the port's own checklist.</p></div>`,
    refs: ["platform/frontend/src/pages/docs/"],
  },
];
